export type UserRole = 'habitant' | 'adherent' | 'soutien' | 'bureau' | 'president';

export type PermissionAction = 'view' | 'create' | 'update' | 'delete' | 'validate' | 'archive';

export type ModuleKey =
  | 'publicHome'
  | 'publicExplorer'
  | 'login'
  | 'habitantLogin'
  | 'bureauHome'
  | 'presidentHome'
  | 'publicRegistration'
  | 'residentSpace'
  | 'publicAnnouncements'
  | 'publicDocuments'
  | 'publicReports'
  | 'publicDouars'
  | 'joinPlatform'
  | 'about'
  | 'oralMemory'
  | 'heritage'
  | 'timeline'
  | 'communityMap'
  | 'projects'
  | 'bureauProjects'
  | 'events'
  | 'bureauEvents'
  | 'youth'
  | 'bureauYouth'
  | 'solidarity'
  | 'bureauSolidarity'
  | 'water'
  | 'bureauWater'
  | 'agriculture'
  | 'bureauAgriculture'
  | 'diaspora'
  | 'bureauDiaspora'
  | 'cooperatives'
  | 'bureauCooperatives'
  | 'registrationRequests'
  | 'bureauAnnouncements'
  | 'bureauDocuments'
  | 'meetingDocuments'
  | 'bureauReports'
  | 'bureauOralMemory'
  | 'bureauHeritage'
  | 'bureauTimeline'
  | 'bureauCommunityMap'
  | 'members'
  | 'contributions'
  | 'contactsAuthorities'
  | 'fieldCollection'
  | 'actionPlan'
  | 'internalTasks'
  | 'administrativeProcedures'
  | 'meetingsDecisions'
  | 'localBackup'
  | 'presidentInternalSteering'
  | 'presidentContentEditor'
  | 'presidentOrchid'
  | 'presidentStrategicDossiers'
  | 'presidentCensus'
  | 'associationRenewal'
  | 'workflows'
  | 'statistics'
  | 'mosque';

export type RoutePath =
  | '/'
  | '/explorer'
  | '/login'
  | '/connexion-habitant'
  | '/bureau'
  | '/president'
  | '/inscription'
  | '/habitant'
  | '/a-propos'
  | '/annonces'
  | '/documents-publics'
  | '/signalement'
  | '/douars'
  | '/douars/:slug'
  | '/rejoindre'
  | '/memoire-orale'
  | '/patrimoine'
  | '/chronologie'
  | '/carte'
  | '/carte-communautaire'
  | '/projets'
  | '/evenements'
  | '/jeunesse'
  | '/entraide'
  | '/eau'
  | '/agriculture'
  | '/diaspora'
  | '/cooperatives'
  | '/membres'
  | '/cotisations'
  | '/bureau/inscriptions'
  | '/bureau/annonces'
  | '/bureau/documents-publics'
  | '/bureau/documents-reunion'
  | '/bureau/signalements'
  | '/bureau/memoire-orale'
  | '/bureau/patrimoine'
  | '/bureau/chronologie'
  | '/bureau/carte-communautaire'
  | '/bureau/projets'
  | '/bureau/evenements'
  | '/bureau/jeunesse'
  | '/bureau/entraide'
  | '/bureau/eau'
  | '/bureau/agriculture'
  | '/bureau/diaspora'
  | '/bureau/cooperatives'
  | '/bureau/contacts'
  | '/bureau/collecte-terrain'
  | '/bureau/plan-action'
  | '/bureau/taches'
  | '/bureau/demarches'
  | '/bureau/reunions'
  | '/bureau/sauvegarde'
  | '/president/pilotage-interne'
  | '/president/editeur-contenu'
  | '/president/orchid'
  | '/president/dossiers-strategiques'
  | '/president/recensement'
  | '/bureau/membres'
  | '/bureau/cotisations'
  | '/bureau/renouvellement'
  | '/bureau/workflows'
  | '/bureau/workflow-publication'
  | '/bureau/statistiques'
  | '/bureau/mosquee';

export const roleLabels: Record<UserRole, { fr: string; ar: string }> = {
  habitant: { fr: 'Habitant', ar: 'ساكن' },
  adherent: { fr: 'Adhérent', ar: 'منخرط' },
  soutien: { fr: 'Soutien', ar: 'داعم' },
  bureau: { fr: 'Bureau', ar: 'المكتب' },
  president: { fr: 'Président', ar: 'الرئيس' },
};

