export const siteConfig = {
  name: import.meta.env.VITE_ASSOCIATION_NAME || 'Community Registry',
  nameAr: import.meta.env.VITE_ASSOCIATION_NAME_AR || 'السجل الجماعي',
  place: import.meta.env.VITE_PLACE_NAME || 'Community Location',
  placeAr: import.meta.env.VITE_PLACE_NAME_AR || 'موقع المجتمع',
  slug: import.meta.env.VITE_ASSOCIATION_SLUG || 'community',
  publicUrl: import.meta.env.VITE_PUBLIC_APP_URL || 'https://app.example.com',
  officialEmail: import.meta.env.VITE_OFFICIAL_EMAIL || 'contact@example.com',
  demoMode: import.meta.env.VITE_DEMO_MODE === 'true',
  demoPresentation: import.meta.env.VITE_DEMO_PRESENTATION === 'true',
  adminPinConfigured: Boolean(import.meta.env.VITE_ADMIN_PIN && import.meta.env.VITE_ADMIN_PIN.length >= 4),
  internalModulesEnabled: import.meta.env.VITE_ENABLE_INTERNAL_MODULES === 'true',
  siteLockEnabled: import.meta.env.VITE_SITE_LOCK_ENABLED === 'true',
  siteLockPasswordHash: import.meta.env.VITE_SITE_LOCK_PASSWORD_HASH?.trim() || '',
  siteLockPassword: import.meta.env.VITE_SITE_LOCK_PASSWORD?.trim() || '',
  siteLockSessionHours: Number(import.meta.env.VITE_SITE_LOCK_SESSION_HOURS || 12),
  isDevelopment: import.meta.env.DEV,
} as const;
